### ISSUE TITLE
xls2yaml doesn't work properly - creates two entries for single hierarchy after xlrd removal

### ISSUE THREAD

**Issue by aburston** [Juniper/nita-yaml-to-excel#5]
# In branch 21.7

For the following spreadsheet:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/aburston/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/aburston/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<body link=blue vlink=purple>

host | interface | ip | vlan_id | esi | system_id | lag_members+.interface | members+.id
-- | -- | -- | -- | -- | -- | -- | --
host_vars/dc1-leaf1.yaml | ae0 |   |   | 00:00:00:00:00:00:00:00:01:00 | 00:00:00:00:01:00 | xe-0/0/2 |  
host_vars/dc1-leaf1.yaml | ae0 |   |   | 00:00:00:00:00:00:00:00:01:00 | 00:00:00:00:01:00 |   | 1001

</body>

</html>

The yaml below is generated:

```
evpn_port:
- esi: 00:00:00:00:00:00:00:00:01:00
  interface: ae0
  ip:
  lag_members:
  - interface: xe-0/0/2
  members:
  - id:
  system_id: 00:00:00:00:01:00
  vlan_id:
- esi: 00:00:00:00:00:00:00:00:01:00
  interface: ae0
  ip:
  lag_members:
  - interface:
  members:
  - id: 1001
  system_id: 00:00:00:00:01:00
  vlan_id:
```

What we actually want (which is the output from the 20.10 version):
```
evpn_port:
- esi: 00:00:00:00:00:00:00:00:01:00
  interface: ae0
  ip:
  lag_members:
  - interface: xe-0/0/2
  members:
  - id: 1001
  system_id: 00:00:00:00:01:00
  vlan_id:
```
